name: asi-ml

channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.11
  - ipykernel
  - jupyterlab
  - numpy
  - pandas
  - pyarrow
  - matplotlib
  - seaborn
  - scikit-learn
  - pandera
  - joblib
  - fastapi
  - uvicorn
  - databases
  - pydantic
  - pydantic-settings
  - asyncpg
  - aiosqlite
  - pip

  - pip:
      - autogluon==1.4.0
      - kedro
      - kedro-datasets[pandas]
      - kedro-datasets[tracking]==2.*
      - kedro-viz
      - wandb
      - pre-commit
      - black
      - ruff
      - pytest
      - httpx

  - requests
  - streamlit
